# -*- coding: utf-8 -*-
"""vs_agent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ziRduKIGQNPknY8ybetIxD0fiU6KIH2v
"""

import google.generativeai as genai
import streamlit as st
import requests
import json
import plotly.graph_objects as go
from fpdf import FPDF
import tempfile
import os

# API Keys — using Streamlit secrets for security
GEMINI_API_KEY = st.secrets["GEMINI_API_KEY"]
SERPER_API_KEY = st.secrets["SERPER_API_KEY"]

# Configure Gemini
genai.configure(api_key=GEMINI_API_KEY)
model = genai.GenerativeModel("gemini-2.5-flash")

# ============ FUNCTIONS ============

def search_startup(startup_name):
    """Search the web for startup information"""
    url = "https://google.serper.dev/search"
    headers = {
        "X-API-KEY": SERPER_API_KEY,
        "Content-Type": "application/json"
    }
    payload = {
        "q": f"{startup_name} startup funding team product market competitors",
        "num": 5
    }
    try:
        response = requests.post(url, headers=headers, json=payload)
        results = response.json()
        search_data = ""
        if "organic" in results:
            for item in results["organic"][:5]:
                search_data += f"Title: {item.get('title', '')}\n"
                search_data += f"Snippet: {item.get('snippet', '')}\n\n"
        return search_data
    except Exception as e:
        return f"Search error: {str(e)}"

def generate_scores(startup_name, search_results):
    """Generate investment scores using Gemini"""
    prompt = f"""
    You are a VC analyst. Based on this information about {startup_name}:
    {search_results}

    Score this startup from 1-10 on each dimension.
    Return ONLY a JSON object with exactly these keys, nothing else, no markdown:
    {{
        "market_opportunity": 7,
        "business_model": 6,
        "team": 8,
        "traction": 5,
        "competitive_advantage": 7,
        "overall": 7
    }}
    """
    try:
        response = model.generate_content(prompt)
        text = response.text.strip()
        if "```" in text:
            text = text.split("```")[1]
            if text.startswith("json"):
                text = text[4:]
        scores = json.loads(text.strip())
        return scores
    except:
        return {
            "market_opportunity": 0,
            "business_model": 0,
            "team": 0,
            "traction": 0,
            "competitive_advantage": 0,
            "overall": 0
        }

def generate_competitors(startup_name, search_results):
    """Generate competitor analysis using Gemini"""
    prompt = f"""
    Based on this information about {startup_name}:
    {search_results}

    Return ONLY a JSON array of the top 3 competitors with exactly this format, no markdown:
    [
        {{"name": "Competitor 1", "description": "Brief description", "threat_level": "High"}},
        {{"name": "Competitor 2", "description": "Brief description", "threat_level": "Medium"}},
        {{"name": "Competitor 3", "description": "Brief description", "threat_level": "Low"}}
    ]
    """
    try:
        response = model.generate_content(prompt)
        text = response.text.strip()
        if "```" in text:
            text = text.split("```")[1]
            if text.startswith("json"):
                text = text[4:]
        competitors = json.loads(text.strip())
        return competitors
    except:
        return [
            {"name": "Competitor 1", "description": "Unable to fetch competitor data", "threat_level": "Medium"},
            {"name": "Competitor 2", "description": "Unable to fetch competitor data", "threat_level": "Medium"},
            {"name": "Competitor 3", "description": "Unable to fetch competitor data", "threat_level": "Low"}
        ]

def generate_investment_memo(startup_name, startup_description, search_results):
    """Generate full investment memo using Gemini"""
    prompt = f"""
    You are an expert venture capital analyst at a top tier VC firm like a16z or Sequoia.

    Generate a comprehensive investment memo for:
    Startup Name: {startup_name}
    Description: {startup_description}
    Web Research: {search_results}

    Structure the memo with these sections:

    ## 1. COMPANY OVERVIEW
    Brief description of what the company does and its mission.

    ## 2. MARKET OPPORTUNITY
    TAM, SAM, SOM analysis with specific numbers where possible.

    ## 3. BUSINESS MODEL
    How the company makes money, pricing strategy, unit economics.

    ## 4. COMPETITIVE LANDSCAPE
    Key competitors, differentiation, moat.

    ## 5. TEAM ASSESSMENT
    Founder backgrounds, relevant experience, key hires.

    ## 6. TRACTION & METRICS
    Revenue, growth, customers, key milestones.

    ## 7. INVESTMENT THESIS
    Why this is a compelling investment opportunity.

    ## 8. KEY RISKS
    Top 3-5 risks and mitigants.

    ## 9. RECOMMENDATION
    Clear invest/pass recommendation with justification.

    Be specific, data driven, and analytical.
    """
    response = model.generate_content(prompt)
    return response.text

def create_radar_chart(scores, startup_name):
    """Create radar chart for scoring dashboard"""
    categories = [
        "Market Opportunity",
        "Business Model",
        "Team",
        "Traction",
        "Competitive Advantage"
    ]
    values = [
        scores["market_opportunity"],
        scores["business_model"],
        scores["team"],
        scores["traction"],
        scores["competitive_advantage"]
    ]
    values.append(values[0])
    categories.append(categories[0])

    fig = go.Figure(data=go.Scatterpolar(
        r=values,
        theta=categories,
        fill='toself',
        line_color='#667eea',
        fillcolor='rgba(102, 126, 234, 0.3)'
    ))
    fig.update_layout(
        polar=dict(radialaxis=dict(visible=True, range=[0, 10])),
        showlegend=False,
        title=f"{startup_name} — Investment Score Dashboard",
        height=400
    )
    return fig

def create_comparison_chart(all_scores):
    """Create comparison radar chart for multiple startups"""
    categories = ["Market", "Business Model", "Team", "Traction", "Competition"]
    score_keys = ["market_opportunity", "business_model", "team", "traction", "competitive_advantage"]
    colors = ['#667eea', '#f093fb', '#4facfe']

    fig = go.Figure()

    for i, (startup, scores) in enumerate(all_scores.items()):
        values = [scores[k] for k in score_keys]
        values.append(values[0])
        cats = categories + [categories[0]]

        fig.add_trace(go.Scatterpolar(
            r=values,
            theta=cats,
            fill='toself',
            name=startup,
            line_color=colors[i % len(colors)]
        ))

    fig.update_layout(
        polar=dict(radialaxis=dict(visible=True, range=[0, 10])),
        title="Startup Comparison Dashboard",
        height=500
    )
    return fig

def export_to_pdf(startup_name, memo, scores):
    """Export investment memo to PDF"""
    pdf = FPDF()
    pdf.add_page()

    # Title
    pdf.set_font("Arial", "B", 18)
    pdf.cell(0, 12, f"Investment Memo: {startup_name}", ln=True)
    pdf.set_font("Arial", "I", 10)
    pdf.cell(0, 8, "Generated by VC Research Agent | Powered by Gemini AI", ln=True)
    pdf.ln(5)

    # Scores section
    pdf.set_font("Arial", "B", 13)
    pdf.cell(0, 10, "Investment Scores", ln=True)
    pdf.set_font("Arial", "", 11)
    score_labels = {
        "overall": "Overall Score",
        "market_opportunity": "Market Opportunity",
        "business_model": "Business Model",
        "team": "Team",
        "traction": "Traction",
        "competitive_advantage": "Competitive Advantage"
    }
    for key, label in score_labels.items():
        pdf.cell(0, 8, f"{label}: {scores.get(key, 'N/A')}/10", ln=True)

    pdf.ln(5)

    # Memo section
    pdf.set_font("Arial", "B", 13)
    pdf.cell(0, 10, "Full Investment Memo", ln=True)
    pdf.set_font("Arial", "", 9)

    for line in memo.split('\n'):
        if line.strip():
            try:
                clean_line = line.encode('latin-1', 'replace').decode('latin-1')
                pdf.multi_cell(0, 6, clean_line)
            except:
                pass

    tmp = tempfile.NamedTemporaryFile(delete=False, suffix='.pdf')
    pdf.output(tmp.name)
    return tmp.name

# ============ STREAMLIT UI ============

st.set_page_config(
    page_title="VC Research Agent",
    page_icon="💼",
    layout="wide"
)

# Header
st.title("💼 VC Research Agent")
st.subheader("Autonomous startup research & investment memo generation powered by Gemini AI")
st.markdown("---")

# Mode selection
mode = st.radio(
    "Select Mode:",
    ["Single Startup Analysis", "Compare Multiple Startups"],
    horizontal=True
)

st.markdown("---")

# ============ SINGLE STARTUP MODE ============
if mode == "Single Startup Analysis":

    col1, col2 = st.columns(2)
    with col1:
        startup_name = st.text_input("🏢 Startup Name", placeholder="e.g. Northspyre")
    with col2:
        startup_description = st.text_area(
            "📝 Brief Description (optional)",
            placeholder="e.g. AI platform for real estate developers",
            height=100
        )

    if st.button("🚀 Generate Full Analysis", use_container_width=True):
        if startup_name:

            # Web search
            with st.spinner("🔍 Searching web for startup information..."):
                search_results = search_startup(startup_name)

            # Generate all data
            with st.spinner("🤖 Analyzing with Gemini AI..."):
                scores = generate_scores(startup_name, search_results)
                competitors = generate_competitors(startup_name, search_results)
                memo = generate_investment_memo(startup_name, startup_description, search_results)

            st.success(f"✅ Analysis complete for {startup_name}!")
            st.markdown("---")

            # Tabs
            tab1, tab2, tab3, tab4 = st.tabs([
                "📊 Score Dashboard",
                "🏆 Competitor Analysis",
                "📄 Investment Memo",
                "📥 Export PDF"
            ])

            with tab1:
                st.subheader(f"Investment Scorecard — {startup_name}")
                col1, col2, col3 = st.columns(3)
                col1.metric("⭐ Overall Score", f"{scores['overall']}/10")
                col2.metric("📈 Market Opportunity", f"{scores['market_opportunity']}/10")
                col3.metric("👥 Team", f"{scores['team']}/10")

                col4, col5 = st.columns(2)
                col4.metric("💰 Business Model", f"{scores['business_model']}/10")
                col5.metric("🚀 Traction", f"{scores['traction']}/10")

                fig = create_radar_chart(scores, startup_name)
                st.plotly_chart(fig, use_container_width=True)

            with tab2:
                st.subheader(f"Competitive Landscape — {startup_name}")
                for comp in competitors:
                    threat_color = {
                        "High": "🔴",
                        "Medium": "🟡",
                        "Low": "🟢"
                    }.get(comp.get('threat_level', 'Medium'), "⚪")

                    with st.expander(
                        f"{threat_color} {comp.get('name', 'Unknown')} — Threat Level: {comp.get('threat_level', 'Medium')}"
                    ):
                        st.write(comp.get('description', 'No description available'))

            with tab3:
                st.subheader(f"Investment Memo — {startup_name}")
                st.markdown(memo)

            with tab4:
                st.subheader("Export to PDF")
                st.write("Download the complete investment memo as a formatted PDF.")
                if st.button("📄 Generate PDF", use_container_width=True):
                    with st.spinner("Creating PDF..."):
                        pdf_path = export_to_pdf(startup_name, memo, scores)
                        with open(pdf_path, "rb") as f:
                            st.download_button(
                                label="📥 Download Investment Memo PDF",
                                data=f,
                                file_name=f"{startup_name}_investment_memo.pdf",
                                mime="application/pdf",
                                use_container_width=True
                            )
                        os.unlink(pdf_path)
        else:
            st.warning("⚠️ Please enter a startup name!")

# ============ COMPARISON MODE ============
else:
    st.subheader("Compare Multiple Startups Side by Side")

    col1, col2, col3 = st.columns(3)
    with col1:
        startup1 = st.text_input("Startup 1", placeholder="e.g. Northspyre")
    with col2:
        startup2 = st.text_input("Startup 2", placeholder="e.g. EliseAI")
    with col3:
        startup3 = st.text_input("Startup 3 (optional)", placeholder="e.g. Cherre")

    if st.button("🔄 Compare Startups", use_container_width=True):
        startups = [s for s in [startup1, startup2, startup3] if s]

        if len(startups) >= 2:
            all_scores = {}

            for startup in startups:
                with st.spinner(f"Analyzing {startup}..."):
                    search_results = search_startup(startup)
                    scores = generate_scores(startup, search_results)
                    all_scores[startup] = scores

            st.success("✅ Comparison complete!")
            st.markdown("---")

            # Comparison radar chart
            fig = create_comparison_chart(all_scores)
            st.plotly_chart(fig, use_container_width=True)

            # Score table
            st.subheader("Score Comparison Table")
            score_keys = ["overall", "market_opportunity", "business_model", "team", "traction", "competitive_advantage"]
            score_labels = ["Overall", "Market", "Business Model", "Team", "Traction", "Competition"]

            cols = st.columns(len(startups))
            for i, (startup, scores) in enumerate(all_scores.items()):
                with cols[i]:
                    st.markdown(f"**{startup}**")
                    for key, label in zip(score_keys, score_labels):
                        st.write(f"**{label}:** {scores.get(key, 'N/A')}/10")

        else:
            st.warning("⚠️ Please enter at least 2 startup names!")

# Footer
st.markdown("---")
st.caption("💼 VC Research Agent | Built with Gemini AI + Serper Web Search | Columbia MS Business Analytics")
